src/Entity/Application.php
<?php

namespace App\Entity;

use App\Repository\ApplicationRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ApplicationRepository::class)]
class Application
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $status = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\ManyToOne(inversedBy: 'applications')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\ManyToOne(inversedBy: 'applications')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Offer $Offer = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $message = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getOffer(): ?Offer
    {
        return $this->Offer;
    }

    public function setOffer(?Offer $Offer): static
    {
        $this->Offer = $Offer;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): static
    {
        $this->message = $message;

        return $this;
    }
}

src/Form/UserProfilType.php
<?php

namespace App\Form;

use App\Entity\User;
use App\Entity\UserProfil;
use Symfony\Component\Form\AbstractType;
use phpDocumentor\Reflection\Types\Boolean;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Validator\Constraints\Image;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TelType;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\CountryType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class UserProfilType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('firstName',TextType::class,[
                'label' => false,
                'attr' => [
                    'placeholder' => 'Entrez votre prénom'
                ]
            ])
            ->add('lastName',TextType::class,[
                'label' => false,
                'attr' => [
                    'placeholder' => 'Entrez votre nom'
                ]
            ])
            ->add('address',TextType::class,[
                'label' => false,
                'attr' => [
                    'placeholder' => 'Entrez votre adresse'
                ]
            ])
            ->add('city',TextType::class,[
                'label' => false,
                'attr' => [
                    'placeholder' => 'Entrez votre ville'
                ]
            ])
            ->add('zipCode',TextType::class,[
                'label' => false,
                'attr' => [
                    'placeholder' => 'Entrez votre code postal'
                ]
            ])
            ->add('country',CountryType::class,[
                'label' => false,
                'preferred_choices' => [
                    'FR',
                    'BE',
                    'CH',
                    'LU',
                    'DE',
                    'IT',
                ]
            ])
            ->add('phoneNumber',TelType::class,[
                'label' => false,
                'attr' => [
                    'placeholder' => 'Entrez votre numéro de téléphone'
                ]
            ])
            ->add('jobSought',TextType::class,[
                'label' => false,
                'attr' => [
                    'placeholder' => 'Entrez le poste recherché'
                ]
            ])
            ->add('presentation',TextareaType::class,[
                'label' => false,
                'attr' => [
                    'placeholder' => 'Présentez-vous en quelques mots',
                    'rows' => 10,
                ],
            ])
            ->add('availability',CheckboxType::class,[
                'label' => 'Êtes-vous disponible ?',
                'attr' => [
                    'placeholder' => 'Êtes-vous disponible ?'
                ],
                'required' => false,
            ])
            ->add('website',UrlType::class,[
                'label' => false,
                'attr' => [
                    'placeholder' => 'Entrez votre site web'
                ]
            ])
            ->add('imageFile',FileType::class,[
                'label' => false,
                'attr' => [
                    'placeholder' => 'Choisissez votre photo de profil'
                ],
                // Ajout de la contrainte de validation avec Assert
                'required' => false,
            'constraints' => [
                new Image([
                    'maxSize' => '3M',
                    'mimeTypes' => [
                        'image/jpg',
                        'image/jpeg',
                        'image/png',
                        'image/webp',
                    ],
                    'mimeTypesMessage' => 'Veuillez uploader une image au format jpg, jpeg, png ou gif',

                ])
            ]


            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => UserProfil::class,
        ]);
    }
}

src/Controller/UserProfilController.php
<?php

namespace App\Controller;

use App\Entity\UserProfil;
use Cocur\Slugify\Slugify;
use App\Form\UserProfilType;
use App\Entity\PasswordUpdate;
use App\Form\UpdatePasswordType;
use App\Repository\ApplicationRepository;
use App\Services\UploadFilesServices;
use Symfony\Component\Form\FormError;
use App\Repository\UserProfilRepository;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasher;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;

// On définit le préfixe de route pour toutes les routes de ce contrôleur
#[Route('/account')]
class UserProfilController extends AbstractController
{
    #[Route('/user/profil', name: 'app_user_profil')]
    public function index(Request $request, UserProfilRepository $userProfilRepository, UploadFilesServices $uploadFilesServices, EntityManagerInterface $em): Response
    {
        // On vérifie que l'utilisateur n'a pas déjà un profil
        $user = $this->getUser();
        if ($user->getUserProfil() !== null) {
            return $this->redirectToRoute('app_user_profil_show', [
                'slug' => $user->getUserProfil()->getSlug(),
                'id' => $user->getUserProfil()->getId()
            ]);
        }

        $userProfil = new UserProfil();

        $form = $this->createForm(UserProfilType::class, $userProfil);

        $form->handleRequest($request);

        $slugify = new Slugify();
        if ($form->isSubmitted() && $form->isValid()) {

            $userProfil->setUser($this->getUser());

            $userProfil->setSlug($slugify->slugify($userProfil->getFirstName() . ' ' . $userProfil->getLastName()));

            //dd($form['imageFile']->getData()); // On récupère l'image
            $file = $form['imageFile']->getData(); // On récupère l'image

            // On sauvegarde l'image
            if ($file) {
                $file_name = $uploadFilesServices->saveFile($file); // On sauvegarde l'image
                $userProfil->setPicture($file_name);
            } else {
                $userProfil->setPicture('default.png');
            }

            // On ajoute l'image à l'entité

            //dd($userProfil);
            $em->persist($userProfil);
            $em->flush();

            notyf()
                ->position('x', 'right')
                ->position('y', 'top')
                ->dismissible(true)
                ->addSuccess('Votre profil a bien été créé.');

            return $this->redirectToRoute('app_user_profil', [
                'id' => $userProfil->getId()
            ]);
        }

        return $this->render('user_profil/index.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    // Cette route permet d'afficher le profil de l'utilisateur connecté
    #[Route('/user/profil/{id}', name: 'app_user_profil_show')]
    public function show(int $id, UserProfilRepository $userProfilRepository): Response
    {
        // Si l'utilisateur connecté n'est pas le propriétaire du profil, on le redirige vers son profil
        $user = $this->getUser();
        $userProfil = $userProfilRepository->find($id);

        // Si l'utilisateur connecté n'est pas le propriétaire du profil, on le redirige vers son profil
        if (!$userProfil || $user->getUserProfil() !== $userProfil) {
            return $this->redirectToRoute('app_user_profil_show', [
                'id' => $user->getUserProfil()->getId()
            ]);
        }

        return $this->render('user_profil/show.html.twig', [
            'userProfil' => $userProfil,
        ]);
    }


    // Cette route permet de modifier le profil de l'utilisateur connecté
    #[Route('/user/profil/{id}/edit', name: 'app_user_profil_edit')]
    public function editUser(Request $request, $id, UserProfilRepository $userProfilRepository, UploadFilesServices $uploadFilesServices, EntityManagerInterface $em): Response
    {
        // Si l'utilisateur connecté n'est pas le propriétaire du profil, on le redirige vers son profil
        $user = $this->getUser();
        $userProfil = $userProfilRepository->find($id);
        if (!$userProfil || $user->getUserProfil() !== $userProfil) {
            return $this->redirectToRoute('app_user_profil_show', [
                'id' => $user->getUserProfil()->getId()
            ]);
        }

        $form = $this->createForm(UserProfilType::class, $userProfil);

        $form->handleRequest($request);

        $slugify = new Slugify();
        if ($form->isSubmitted() && $form->isValid()) {

            $userProfil->setUser($this->getUser());

            $userProfil->setSlug($slugify->slugify($userProfil->getFirstName() . ' ' . $userProfil->getLastName()));

            // Si l'utilisateur a ajouté une nouvelle image
            $file = $form['imageFile']->getData();

            if ($file) {
                $file_name = $uploadFilesServices->updateFile($file, $userProfil->getPicture()); // On met à jour l'image
                $userProfil->setPicture($file_name); // On ajoute l'image à l'entité
            }

            //dd($userProfil);
            $em->persist($userProfil);
            $em->flush();

            notyf()
                ->position('x', 'right')
                ->position('y', 'top')
                ->dismissible(true)
                ->addSuccess('Votre profil a bien été modifié.');

            return $this->redirectToRoute('app_user_profil_show', [
                'id' => $userProfil->getId()
            ]);
        }

        return $this->render('user_profil/edit.html.twig', [
            'form' => $form->createView(),
        ]);
    }


    // Cette route permet de supprimer le profil de l'utilisateur connecté
    #[Route('/user/profil/{id}/delete', name: 'app_user_profil_delete')]
    public function delete(int $id, UserProfilRepository $userProfilRepository, EntityManagerInterface $em, TokenStorageInterface $tokenStorage, SessionInterface $session, UploadFilesServices $uploadFilesServices): Response
    {
        // Si l'utilisateur connecté n'est pas le propriétaire du profil, on le redirige vers son profil
        $user = $this->getUser();
        $userProfil = $userProfilRepository->find($id);
        if (!$userProfil || $user->getUserProfil() !== $userProfil) {
            return $this->redirectToRoute('app_user_profil_show', [
                'id' => $user->getUserProfil()->getId()
            ]);
        }

        // On supprime l'image du dossier uploads
        if ($userProfil->getPicture() !== 'default.png') {
            $uploadFilesServices->deleteFile($userProfil->getPicture());
        }

        $em->remove($userProfil);
        $em->flush();



        // Déconnecter l'utilisateur
        $tokenStorage->setToken(null);

        // Invalidate session afin que l'utilisateur ne puisse pas accéder à la page de son profil
        $session->invalidate();
        return $this->redirectToRoute('app_home');
    }

    // Cette route permet de modifier le profil de l'utilisateur connecté depuis la page de son profil

    #[Route('/user/profil/{id}/update-password', name: 'app_user_profil_update_password')]
    public function updatePassword(Request $request, EntityManagerInterface $em, UserPasswordHasherInterface $userPasswordHasherInterface,UserRepository $userRepository): Response
    {
        $user = $this->getUser();

        $passwordUpdate = new PasswordUpdate();
        $form = $this->createForm(UpdatePasswordType::class, $passwordUpdate);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // Définir les valeurs de oldPassword, newPassword et confirmPassword dans l'objet PasswordUpdate
            $passwordUpdate = $form->getData();

            // Créer une variable pour stocker le mot de passe de l'utilisateur
            $oldPassword = $passwordUpdate->getOldPassword();
            $newPassword = $passwordUpdate->getNewPassword();
            $confirmPassword = $passwordUpdate->getConfirmPassword();

            // Vérifier que le mot de passe saisi correspond bien au mot de passe de l'utilisateur

            if (!password_verify($oldPassword, $user->getPassword())) {
                //Ici on récupère le champ oldPassword et on lui ajoute une erreur avec addError et on lui passe un nouvel objet FormError avec un message d'erreur
                $form->get('oldPassword')
                    ->addError(
                        new FormError(
                            'Le mot de passe saisi ne correspond pas à votre mot de passe actuel.'
                        )
                    );
            } else {
                // hasher le nouveau mot de passe
                $newPasswordHash = $userPasswordHasherInterface->hashPassword($user, $newPassword);
                $user->setPassword($newPasswordHash);
                $em->persist($user);
                $em->flush();

                notyf()
                    ->position('x', 'right')
                    ->position('y', 'top')
                    ->dismissible(true)
                    ->addSuccess('Votre mot de passe a bien été modifié.');

                return $this->redirectToRoute('app_user_profil_show', [
                    'id' => $user->getUserProfil()->getId()
                ]);
            }
        }

        return $this->render('user_profil/update_password.html.twig', [
            'form' => $form->createView(),
        ]);
    } 


    // Cette route va permettre à l'utilisateur connecté de de voir ses candidatures

templates/user_profil/applications.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{{ parent() }}
	| Mes candidatures
{% endblock %}

{% block body %}
	<div class="container-fluid">
		<div class="row">
			<div class="col-2 bg-dark text-white">
				{% include 'partials/_sidebar.html.twig' %}
			</div>
			<div class="col-10 bg-custom-account">
				{% block content %}
					<h2 class="text-center">Mes candidatures</h2>
					{% if applications|length == 0 %}
						<div class="alert alert-info">
							Aucune candidature n'a été trouvée.
						</div>
					{% else %}
						<h6 class="text-center">
							Vous avez postulé à
							{{ applications|length == 1 ? 'une offre' : applications|length ~ ' offres' }}.
						</h6>
						<div class="table-responsive">
							<table class="table table-striped table-hover table-bordered table-dark text-center">
								<thead>
									<tr>
										<th>Statut</th>
										<th>Offre</th>
										<th>Entreprise</th>
										<th>Contrat</th>
										<th>Localisation</th>
										<th>Date</th>
									</tr>
								</thead>
								<tbody>
									{% for application in applications %}
										<tr class="table-active">
											<td>
												{% if application.status == 'STATUS_ACCEPTED' %}
													<span class="badge text-bg-success">Acceptée</span>
												{% elseif application.status == 'STATUS_REFUSED' %}
													<span class="badge text-bg-danger">Refusée</span>
												{% else %}
													<span class="badge text-bg-info">En attente</span>
												{% endif %}
											</td>
											<td>
												<a href="{{ path('app_offre_emploi_show', {'id': application.offer.id,'slug':application.offer.slug}) }}" class="text-white text-decoration-none">
													{{ application.offer.title }}
												</a>
											</td>
											<td>{{ application.offer.entreprise.name }}</td>
											<td>{{ application.offer.contractType }}</td>
											<td>{{ application.offer.location }}</td>
											<td>{{ application.offer.createdAt|date('d/m/Y') }}</td>
										</tr>
									{% endfor %}
								</tbody>
							</table>
						</div>
					{% endif %}
				{% endblock %}
			</div>
		</div>
	</div>
{% endblock %}

templates/user_profil/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{{ parent() }}
	| Mon compte
{% endblock %}

{% block body %}
	<div class="container-fluid">
		<div class="row">
			<div class="col-2 bg-dark text-white">
				{% include 'partials/_sidebar.html.twig' %}
			</div>
			<div class="col-10 bg-custom-account">
				{% block content %}
					<div class="row">
						<div class="col-12">
							<h1 class="text-center">
								Création de mon profil candidat
							</h1>
						</div>

						<class="col-12">
							{{ form_start(form) }}

							<div class="row g-3">
								<div class="col">
									{{ form_row(form.firstName) }}
								</div>
								<div class="col">
									{{ form_row(form.lastName) }}
								</div>
							</div>

							<div class="row g-3">
								<div class="col">{{ form_row(form.phoneNumber) }}</div>
								<div class="col">{{ form_row(form.address) }}</div>
							</div>

							<div class="row g-3">

								<div class="col">{{ form_row(form.city) }}</div>

								<div class="col">{{ form_row(form.zipCode) }}</div>

								<div class="col">{{ form_row(form.country) }}</div>
							</div>

							<div class="row g-3">
								<div class="col">{{ form_row(form.jobSought)}}</div>
								<div class="col">{{ form_row(form.website) }}</div>
							</div>

							{{ form_row(form.availability) }}
							{{ form_row(form.presentation) }}
							{{ form_row(form.imageFile) }}

							<button class="btn btn-warning"> Modifier
                            </button>
							{{ form_end(form) }}
						</div>
					</div>
				{% endblock %}
			</div>

		</div>
	{% endblock %}

templates/user_profil/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{{ parent() }}
	| Mon compte
{% endblock %}

{% block body %}
	<div class="container-fluid">
		<div class="row">
			<div class="col-2 bg-dark text-white">
				{% include 'partials/_sidebar.html.twig' %}
			</div>
			<div class="col-10 bg-custom-account">
				{% block content %}
					<div class="row">
						<div class="col-12">
							<h1 class="text-center">
								Création de mon profil candidat
							</h1>
						</div>

						<class="col-12">
							{{ form_start(form) }}

							<div class="row g-3">
								<div class="col">
									{{ form_row(form.firstName) }}
								</div>
								<div class="col">
									{{ form_row(form.lastName) }}
								</div>
							</div>

							<div class="row g-3">
								<div class="col">{{ form_row(form.phoneNumber) }}</div>
								<div class="col">{{ form_row(form.address) }}</div>
							</div>

							<div class="row g-3">

								<div class="col">{{ form_row(form.city) }}</div>

								<div class="col">{{ form_row(form.zipCode) }}</div>

								<div class="col">{{ form_row(form.country) }}</div>
							</div>

							<div class="row g-3">
								<div class="col">{{ form_row(form.jobSought)}}</div>
								<div class="col">{{ form_row(form.website) }}</div>
							</div>

							{{ form_row(form.availability) }}
							{{ form_row(form.presentation) }}
							{{ form_row(form.imageFile) }}

							<button class="btn btn-success">Créer mon profil</button>
							{{ form_end(form) }}
						</div>
					</div>
					{% endblock %}
				</div>

			</div>
		{% endblock %}

templates/user_profil/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{{ parent() }}
	| Mon compte
{% endblock %}

{% block body %}
	<div class="container-fluid">
		<div class="row">
			<div class="col-2 bg-dark text-white">
				{% include 'partials/_sidebar.html.twig' %}
			</div>
			<div class="col-10 bg-custom-account">
				{% block content %}

				{% if app.user %}
					{% set user = app.user.userProfil %}

					<div class="container mt-5">
						<h1 class="mb-4 text-center">
							Poste recherché:
							<span class="badge bg-secondary">{{ user.jobSought }}</span>
						</h1>
						<div class="card card-text">
							<div class="card-body d-flex justify-content-between">

								<div
									class="col-md-4">
									{# <img src="{{ asset('uploads/'~ user.picture ) }}" alt="Photo de profil" class="img-fluid rounded shadow-lg"> #}
									{% if 'https://api.dicebear.com/' in user.picture %}
										<img src="{{ user.picture}}" alt="Photo de profil" class="img-fluid rounded shadow-lg">
									{% else %}
										<img src="{{ asset('uploads/'~ user.picture ) }}" alt="Photo de profil" class="img-fluid rounded shadow-lg">
									{% endif %}
								</div>

								<div class="col-md-4">
									<h4 class="card-title">
										{{ user.firstName }}
										{{ user.lastName }}
									</h4>
									<strong></strong>
									<details>
										<summary>Adresse:</summary>
										{{ user.address }}
										{{ user.city }}
										{{ user.zipCode }}
										{{ user.country }}
									</details>
									<strong>Tel:</strong>
									{{ user.phoneNumber }}
									<br>
									<strong>Site web:</strong>
									<a href="{{ user.website }}" target="_blank" class="text-decoration-none">Mon portfolio</a>
									<br>
									<p>
										{% if(user.availability == 1) %}
											<span class="badge bg-success">Disponible</span>
										{% else %}
											<span class="badge bg-danger">Indisponible</span>
										{% endif %}
									</p>
								</div>

							</div>
							<div class="card-body">
								<strong class="fs-5">Qui suis-je ?:</strong>
								<p class="card-text mt-3">{{ user.presentation }}</p>

								<a href="{{path('app_user_profil_edit',{'id':user.id})}}" class="btn btn-warning mt-3">
									<i class="bi bi-pencil-square"></i>
								</a>
								<a href="{{path('app_user_profil_delete',{'id':user.id})}}" class="btn btn-danger mt-3">
									<i class="bi bi-trash"></i>
								</a>
							</div>

						</div>


					</div>
				</div>


			{% endif %}
		{% endblock %}
	</div>
</p></div>{% endblock %}

templates/user_profil/update_password.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{{ parent() }}
	| Mon compte
{% endblock %}

{% block body %}
	<div class="container-fluid">
		<div class="row">
			<div class="col-2 bg-dark text-white">
				{% include 'partials/_sidebar.html.twig' %}
			</div>
			<div class="col-10 bg-custom-account">
				{% block content %}
					<div class="row justify-content-center align-items-center mt-5">
						<div class="col-md-6 shadow-lg border border-white p-3 rounded mt-5">

							<div class="row">
								<div class="col-12">
									<h1 class="text-center mt-5">
										Modification de mot de passe
									</h1>
								</div>
								<div class="col-12 p-5">
									{{ form_start(form) }}
									{{ form_row(form.oldPassword) }}
									{{ form_row(form.newPassword) }}
									{{ form_row(form.confirmPassword) }}
									<button type="submit" class="btn btn-primary">Modifier</button>
									{{ form_end(form) }}
								</div>


							</div>
						</div>
					</div>
				{% endblock %}
			</div>

		</div>
	{% endblock %}